/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.database;

import database.databaseStruct.TableStructInterface;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sqlconnector.Sql;
import sqlconnector.SqlConnector;

/**
 *
 * @author User
 */
public class NewRecord extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewRecord
     */
    public NewRecord() {
        initComponents();
    }

    public NewRecord(TableStructInterface struct) {
        initComponents();
        this.struct = struct;
        addDone.setVisible(false);
        clearTable();
    }

    private void clearTable() {
        String[] columns = struct.getColumnTable();
        tableName.setText("DODAJ NOWY REKORD DO TABELI: " + struct.getDataBaseTableNameDisplay());
        insertTable.setModel(new DefaultTableModel(new Object[1][columns.length], columns));
        insertTable.repaint();      
    }
    
    TableStructInterface struct;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        insertTable = new javax.swing.JTable();
        tableName = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        addNewRecord = new javax.swing.JButton();
        addDone = new javax.swing.JLabel();

        insertTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(insertTable);

        tableName.setText("DODAJ NOWY REKORD DO TABELI: ");

        closeButton.setText("Zamknij");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        addNewRecord.setText("Dodaj");
        addNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRecordActionPerformed(evt);
            }
        });

        addDone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addDone.setForeground(new java.awt.Color(255, 51, 0));
        addDone.setText("Rekord Dodany");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addNewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addDone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(closeButton)))
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tableName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(addNewRecord)
                    .addComponent(addDone))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRecordActionPerformed
        addNewRecord.setEnabled(false);
        List<String> params = struct.getColumnTableAsList();
        List<String> values = new ArrayList();
        
        params.remove(0);
        
        for(int i=1; i<struct.getValues().length; i++){
            values.add((String)insertTable.getValueAt(0, i));
        }
        
        String sql = Sql.getInsertQuery(struct.getDataBaseTableName(), params, values);
        if(SqlConnector.doQuery(sql)) {
            addNewRecord.setEnabled(true);
            addDone.setVisible(true);
        } else {
            addNewRecord.setEnabled(true);
        }
        
    }//GEN-LAST:event_addNewRecordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDone;
    private javax.swing.JButton addNewRecord;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable insertTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tableName;
    // End of variables declaration//GEN-END:variables
}
