/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.deliveries;

import database.databaseStruct.TableStructInterface;
import gui.Frame;
import gui.Window;
import gui.items.ItemsInStruct;
import gui.items.ItemsViewType;
import gui.items.ItemsWindow;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import sqlconnector.Sql;
import sqlconnector.SqlConnector;

/**
 *
 * @author User
 */
public class DeliveryViewWindow extends Frame implements Window {

    private DeliveryViewWindowType viewType = DeliveryViewWindowType.NEW_DELIVERY;
    private Frame parent = null;
    
    public DeliveryViewWindow(Frame parent, DeliveryViewWindowType viewType) {
        initComponents();
        this.viewType = viewType;
        name = "DELIVERIES";
        this.parent = parent;
        setParams();
        createTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        deliveryId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        supplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemCode = new javax.swing.JTextField();
        searchItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        itemAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        itemPrice = new javax.swing.JTextField();
        addItem = new javax.swing.JButton();
        deleteRow = new javax.swing.JButton();
        supplierSearch = new javax.swing.JButton();
        addDelivery = new javax.swing.JButton();
        closeDelivery = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            null,
            ItemsInStruct.getValuesAsString()
        ));
        jScrollPane1.setViewportView(itemsTable);

        jLabel1.setText("DELIVERY ID");

        jLabel2.setText("SUPPLIER");

        supplier.setEnabled(false);

        jLabel3.setText("ITEM CODE");

        itemCode.setEnabled(false);
        itemCode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemCodePropertyChange(evt);
            }
        });

        searchItem.setText("SEARCH");
        searchItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchItemMouseReleased(evt);
            }
        });

        jLabel4.setText("ITEM AMOUNT");

        jLabel5.setText("ITEM PRICE");

        addItem.setText("ADD");
        addItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addItemMouseReleased(evt);
            }
        });

        deleteRow.setText("DELETE SELECTED");
        deleteRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteRowMouseReleased(evt);
            }
        });
        deleteRow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deleteRowStateChanged(evt);
            }
        });
        deleteRow.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                deleteRowPropertyChange(evt);
            }
        });

        supplierSearch.setText("SEARCH");

        addDelivery.setText("ADD DELIVERY");
        addDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addDeliveryMouseReleased(evt);
            }
        });

        closeDelivery.setText("CLOSE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deliveryId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(itemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(deleteRow, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItem)
                    .addComponent(jLabel4)
                    .addComponent(itemAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(itemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItem)
                    .addComponent(deleteRow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDelivery)
                    .addComponent(closeDelivery)))
        );

        if(viewType == DeliveryViewWindowType.NEW_DELIVERY) {
            deleteRow.setEnabled(true);
        } else {
            deleteRow.setEnabled(false);
        }
        if(viewType == DeliveryViewWindowType.NEW_DELIVERY) {
            addDelivery.setVisible(true);
        } else {
            addDelivery.setVisible(false);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseReleased
        Vector vector = new Vector();
        vector.add(itemCode.getText()); 
        vector.add(itemAmount.getText());
        vector.add(itemPrice.getText());
        
        DefaultTableModel model = (DefaultTableModel) itemsTable.getModel();
        model.addRow(vector);
    }//GEN-LAST:event_addItemMouseReleased

    private void searchItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchItemMouseReleased
        this.getContentPane().add(new ItemsWindow(this, ItemsViewType.SELECT), 0);
        this.repaint();
        this.setWindowState(false);
    }//GEN-LAST:event_searchItemMouseReleased

    private void itemCodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemCodePropertyChange
        itemCode.setEnabled(false);
    }//GEN-LAST:event_itemCodePropertyChange

    private void deleteRowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRowMouseReleased
        DefaultTableModel model = (DefaultTableModel)itemsTable.getModel();
        model.removeRow(itemsTable.getSelectedRow());
    }//GEN-LAST:event_deleteRowMouseReleased

    private void deleteRowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deleteRowStateChanged
     
    }//GEN-LAST:event_deleteRowStateChanged

    private void deleteRowPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_deleteRowPropertyChange

    }//GEN-LAST:event_deleteRowPropertyChange

    private void addDeliveryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDeliveryMouseReleased
        String id = deliveryId.getText();
        if(id.equals("")) { return; }
        
        String sup = supplier.getText();
        if(sup.equals("")) { return; }
        
        String code = itemCode.getText();
        if(code.equals("")) { return; }
        
        String amount = itemAmount.getText();     
        if(amount.equals("")) { return; }
        
        BigDecimal price = new BigDecimal(itemPrice.getText());
          
        //Dodajemy delivery do deliveries
        Map<TableStructInterface, Object> values = new HashMap();
        values.put(DeliveriesStruct.DELIVERY_ID, id);
        values.put(DeliveriesStruct.SUPPLIER, sup);
        String sqlReplace = Sql.getReplaceIntoQuery(DeliveriesStruct.getTableName(), values);
        if(!SqlConnector.doInsertQuery(sqlReplace)) {
            return;
        }
        
        //Dodajemy itemy do orderu        
        values = new HashMap();
        values.put(ItemsInStruct.ITEM_ORDER_ID, id);
        values.put(ItemsInStruct.ITEM_CODE, code);
        values.put(ItemsInStruct.ITEM_AMOUNT, amount);
        values.put(ItemsInStruct.ITEM_PRICE, price);
        
        values.put(ItemsInStruct.ITEM_ACTUAL_AMOUNT, amount);
        values.put(ItemsInStruct.ITEM_SUM_PRICE, price.multiply( new BigDecimal(amount)));
        
        sqlReplace = Sql.getReplaceIntoQuery(ItemsInStruct.getTableName(), values);
        SqlConnector.doInsertQuery(sqlReplace);
        
        this.dispose();
        parent.setWindowState(true);
    }//GEN-LAST:event_addDeliveryMouseReleased

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

    }//GEN-LAST:event_formInternalFrameClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDelivery;
    private javax.swing.JButton addItem;
    private javax.swing.JButton closeDelivery;
    private javax.swing.JButton deleteRow;
    private javax.swing.JTextField deliveryId;
    private javax.swing.JTextField itemAmount;
    private javax.swing.JTextField itemCode;
    private javax.swing.JTextField itemPrice;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchItem;
    private javax.swing.JTextField supplier;
    private javax.swing.JButton supplierSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setResult() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setResult(Object singleResult) {
        itemCode.setText(singleResult.toString());
    }

    @Override
    public void setResult(Map<Object, String> resultMap) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void doAction(String action) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void createTable() {
        String[] itemTableStruct;
        if(viewType == DeliveryViewWindowType.VIEW_DELIVERY) {
            itemTableStruct = ItemsInStruct.getSelectTableStruct();
        } else {
            itemTableStruct = ItemsInStruct.getInsertTableStruct();
        }

        DefaultTableModel model = new DefaultTableModel(null, itemTableStruct);
        
        itemsTable.setModel(model);
    }
}
