/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.allegro;

import allegro.AllegroApi;

/**
 *
 * @author User
 */
public class AllegroMenu extends javax.swing.JInternalFrame {

    private CreateAuctionInternalFrame createAuction = new CreateAuctionInternalFrame();
    /**
     * Creates new form AllegroMenu
     */
    public AllegroMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newAuction = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        doGetSiteJournalDeals = new javax.swing.JButton();
        doGetMySellItems = new javax.swing.JButton();
        doGetCatsData = new javax.swing.JButton();
        doGetSellFormFieldsForCategory = new javax.swing.JButton();

        newAuction.setText("Nowa Aukcja");
        newAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAuctionActionPerformed(evt);
            }
        });

        jButton2.setText("Wyszukiwanie Aukcji");

        doGetSiteJournalDeals.setText("doGetSiteJournalDeals");
        doGetSiteJournalDeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGetSiteJournalDealsActionPerformed(evt);
            }
        });

        doGetMySellItems.setText("doGetMySellItems");
        doGetMySellItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGetMySellItemsActionPerformed(evt);
            }
        });

        doGetCatsData.setText("doGetCatsData");
        doGetCatsData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGetCatsDataActionPerformed(evt);
            }
        });

        doGetSellFormFieldsForCategory.setText("doGetSellFormFieldsForCategory");
        doGetSellFormFieldsForCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGetSellFormFieldsForCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newAuction, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(doGetSiteJournalDeals, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doGetMySellItems)
                    .addComponent(doGetCatsData)
                    .addComponent(doGetSellFormFieldsForCategory))
                .addGap(0, 739, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(newAuction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doGetSiteJournalDeals)
                .addGap(118, 118, 118)
                .addComponent(doGetMySellItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doGetCatsData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doGetSellFormFieldsForCategory)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAuctionActionPerformed
        createAuction.setVisible(true);
    }//GEN-LAST:event_newAuctionActionPerformed

    private void doGetSiteJournalDealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doGetSiteJournalDealsActionPerformed
        AllegroApi allegroApi = new AllegroApi();
        allegroApi.doGetSiteJournalDeals();
    }//GEN-LAST:event_doGetSiteJournalDealsActionPerformed

    private void doGetMySellItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doGetMySellItemsActionPerformed
        AllegroApi allegroApi = new AllegroApi(); 
        allegroApi.doGetMySellItems(0);
    }//GEN-LAST:event_doGetMySellItemsActionPerformed

    private void doGetCatsDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doGetCatsDataActionPerformed
        AllegroApi allegroApi = new AllegroApi(); 
        allegroApi.doGetCatsData();        
    }//GEN-LAST:event_doGetCatsDataActionPerformed

    private void doGetSellFormFieldsForCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doGetSellFormFieldsForCategoryActionPerformed
        AllegroApi allegroApi = new AllegroApi(); 
        allegroApi.doGetSellFormFieldsForCategory(15046);  
    }//GEN-LAST:event_doGetSellFormFieldsForCategoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doGetCatsData;
    private javax.swing.JButton doGetMySellItems;
    private javax.swing.JButton doGetSellFormFieldsForCategory;
    private javax.swing.JButton doGetSiteJournalDeals;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton newAuction;
    // End of variables declaration//GEN-END:variables
}
